mod 'boxen',             '1.2.0', :github_tarball => 'boxen/puppet-boxen'
mod 'keyremap4macbook',  '1.0.2', :github_tarball => 'boxen/puppet-keyremap4macbook'
mod 'pckeyboardhack',    '1.0.1', :github_tarball => 'smh/puppet-pckeyboardhack'
mod 'stdlib',            '3.0.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
